// Generated by CoffeeScript 1.8.0
(function() {
  var canvas, ctx, getPixel, image, loadingEl, setPixel, start;

  canvas = document.getElementById('canvas');

  ctx = canvas.getContext('2d');

  loadingEl = document.getElementById('loading');

  image = new Image;

  image.addEventListener('load', function() {
    return start();
  });

  image.src = canvas.querySelector('img').src;

  start = function() {
    var line, pixel1, pixel2, x, y, _i, _ref, _results;
    canvas.width = image.width;
    canvas.height = image.height;
    ctx.drawImage(image, 0, 0);
    _results = [];
    for (y = _i = 0, _ref = image.height; 0 <= _ref ? _i <= _ref : _i >= _ref; y = 0 <= _ref ? ++_i : --_i) {
      console.log("" + y + " / " + image.height + " lines");
      line = ctx.getImageData(0, y, image.width, 1);
      x = 1;
      while (x < line.width) {
        pixel1 = getPixel(line, x, 0);
        pixel2 = getPixel(line, x - 1, 0);
        if (x > 0 && pixel1[0] + pixel1[1] + pixel1[2] > pixel2[0] + pixel2[1] + pixel2[2]) {
          setPixel(line, x, 0, pixel2);
          setPixel(line, x - 1, 0, pixel1);
          x--;
        } else {
          x++;
        }
      }
      _results.push(ctx.putImageData(line, 0, y));
    }
    return _results;
  };

  getPixel = function(imageData, x, y) {
    var d, i;
    i = y * imageData.width * 4 + x * 4;
    d = imageData.data;
    return [d[i], d[i + 1], d[i + 2], d[i + 3]];
  };

  setPixel = function(imageData, x, y, pixel) {
    var d, i;
    i = y * imageData.width * 4 + x * 4;
    d = imageData.data;
    d[i] = pixel[0];
    d[i + 1] = pixel[1];
    d[i + 2] = pixel[2];
    return d[i + 3] = pixel[3];
  };

}).call(this);
